###################
### MY PROGRAMS ###
###################

$terminal = alacritty
$fileManager = nautilus
$menu = rofi -show drun
$gemini = gtk-launch chrome-gdfaincndogidkdcdkhapmbffkckdkhn-Default.desktop
$dock = nwg-dock-hyprland -d -i 30 -hd 0
$osd = ~/.config/hypr/scripts/osd.sh
$floating = ~/.config/hypr/scripts/floating.sh
$minimize = ~/.config/hypr/scripts/minimize.sh
$opaque = ~/.config/hypr/scripts/toggleopaque.sh
$clipboard = cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy
$scrnsht = grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/Screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy
$confirm = ~/.config/hypr/scripts/confirm.sh
$ctrlcntr = eww open --toggle control_center
