# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrulev2 = float, class:^(Alacritty)$
windowrulev2 = float, class:^(foot)$
windowrulev2 = float, class:^(kitty)$
windowrulev2 = size 900 600, class:.*
windowrulev2 = opacity 1.0 override 1.0 override, class:^(org.inkscape.Inkscape)$
windowrulev2 = opacity 1.0 override 1.0 override, class:^(Alacritty)$
windowrulev2 = opacity 1.0 override 1.0 override, class:^(foot)$
windowrulev2 = opacity 1.0 override 1.0 override, class:^(kitty)$

windowrulev2 = float, title:^(Open File)(.*)$
windowrulev2 = float, title:^(Open Folder)(.*)$
windowrulev2 = float, title:^(Save As)(.*)$
windowrulev2 = float, title:^(Select a File)(.*)$
windowrulev2 = float, title:^(Choose wallpaper)(.*)$
windowrulev2 = float, title:^(Open)(.*)$
windowrulev2 = float, title:^(Save)(.*)$

windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = float, class:^(xdg-desktop-portal-kde)$
